baseURL = "apozdniakov.com"
languageCode = "en-us"
title = "apozdniakov.com"
themesDir = "themes"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/main.svg"
    mobile_height = "48"
    desktop = "images/logo/main.svg"
    desktop_height = "48"
    alt = "apozdniakov"

  [params.seo]
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'All rights reserved'

[menu]
  # Main Menu

  [[menu.main]]
      name = "Blog"
      url = "https://blog.apozdniakov.com"
      weight = 3

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
